source 'http://rubygems.org'

gem 'sinatra'
gem 'sinatra-contrib'
gem 'sinatra-flash'
gem 'json'
gem "bson_ext", "~> 1.8.2"
gem "mongo", "~> 1.8.2"
gem 'mongo_mapper'
gem 'faraday'
gem 'xml-simple'
gem 'nokogiri'
gem 'jsmin'
gem 'cssmin'
gem 'chronic'